packages:
  - apps/*
  - packages/*
  - tests/*

ignoredBuiltDependencies:
  - electron-winstaller

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - better-sqlite3
  - detox
  - dtrace-provider
  - electron
  - esbuild
  - sqlite3
  - unrs-resolver
