packages:
  - apps/*
  - packages/*
  - tests/*

ignoredBuiltDependencies:
  - electron-winstaller

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - detox
  - dtrace-provider
  - electron
  - esbuild
  - unrs-resolver
