import { PlatformType } from '../../../../constants/platform/PlatformType';
import type { PlatformCapabilityId } from '../../../../types/platform/PlatformCapabilityId';
import type { CompositionMapping } from './CompositionMapping';

/**
 * Predefined composition mappings for complex platform capabilities.
 * These mappings define how complex capabilities can be broken down into
 * simpler, composable components when the original capability is unavailable.
 */
export const capabilityCompositionMappings: CompositionMapping[] = [
  // Rich Text Editor composition
  {
    complexCapability: 'ui.rich-editor' as PlatformCapabilityId,
    supportedPlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
    functionalCoverage: 'substantial',
    implementationComplexity: 'high',
    performanceComparison: 'worse',
    componentCapabilities: [
      {
        capabilityId: 'ui.text-input' as PlatformCapabilityId,
        name: 'Text Input',
        description: 'Basic text input and editing functionality',
        required: true,
        integrationRole: 'primary',
        dependsOn: [],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'minimal',
        implementationHint: 'Use contentEditable div or textarea element',
      },
      {
        capabilityId: 'ui.text-formatting' as PlatformCapabilityId,
        name: 'Text Formatting',
        description: 'Bold, italic, underline, and other text formatting options',
        required: false,
        integrationRole: 'secondary',
        dependsOn: ['ui.text-input' as PlatformCapabilityId],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'moderate',
        implementationHint: 'Use execCommand API or custom formatting logic',
      },
      {
        capabilityId: 'ui.selection-api' as PlatformCapabilityId,
        name: 'Text Selection',
        description: 'Text selection and cursor management',
        required: true,
        integrationRole: 'secondary',
        dependsOn: ['ui.text-input' as PlatformCapabilityId],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'moderate',
        implementationHint: 'Use Selection API and Range objects',
      },
      {
        capabilityId: 'ui.undo-redo' as PlatformCapabilityId,
        name: 'Undo/Redo',
        description: 'Command history and undo/redo functionality',
        required: false,
        integrationRole: 'auxiliary',
        dependsOn: ['ui.text-input' as PlatformCapabilityId],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'significant',
        implementationHint: 'Implement command pattern with history stack',
      },
    ],
    integrationNotes:
      'Rich text editing requires careful integration of multiple components and state management',
  },

  // File Manager composition
  {
    complexCapability: 'ui.file-manager' as PlatformCapabilityId,
    supportedPlatforms: [PlatformType.WEB, PlatformType.CAPACITOR],
    functionalCoverage: 'partial',
    implementationComplexity: 'high',
    performanceComparison: 'worse',
    componentCapabilities: [
      {
        capabilityId: 'ui.file-input' as PlatformCapabilityId,
        name: 'File Input',
        description: 'Basic file selection and upload',
        required: true,
        integrationRole: 'primary',
        dependsOn: [],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'minimal',
        implementationHint: 'Use HTML input[type="file"] element',
      },
      {
        capabilityId: 'ui.drag-drop' as PlatformCapabilityId,
        name: 'Drag and Drop',
        description: 'Drag and drop file operations',
        required: false,
        integrationRole: 'secondary',
        dependsOn: [],
        availablePlatforms: [PlatformType.WEB, PlatformType.ELECTRON],
        implementationEffort: 'moderate',
        implementationHint: 'Use HTML5 Drag and Drop API',
      },
      {
        capabilityId: 'ui.file-preview' as PlatformCapabilityId,
        name: 'File Preview',
        description: 'Preview of file contents and metadata',
        required: false,
        integrationRole: 'auxiliary',
        dependsOn: ['ui.file-input' as PlatformCapabilityId],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'significant',
        implementationHint: 'Use FileReader API for preview generation',
      },
      {
        capabilityId: 'storage.local' as PlatformCapabilityId,
        name: 'Local Storage',
        description: 'Store file metadata and preferences',
        required: false,
        integrationRole: 'auxiliary',
        dependsOn: [],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'minimal',
        implementationHint: 'Use localStorage for file management state',
      },
    ],
    integrationNotes: 'Web-based file management is limited by browser security restrictions',
  },

  // Advanced Data Visualization composition
  {
    complexCapability: 'ui.data-visualization' as PlatformCapabilityId,
    supportedPlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
    functionalCoverage: 'complete',
    implementationComplexity: 'medium',
    performanceComparison: 'similar',
    componentCapabilities: [
      {
        capabilityId: 'ui.canvas' as PlatformCapabilityId,
        name: 'Canvas Drawing',
        description: 'Low-level drawing and rendering capabilities',
        required: true,
        integrationRole: 'primary',
        dependsOn: [],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'moderate',
        implementationHint: 'Use HTML5 Canvas or SVG for custom visualizations',
      },
      {
        capabilityId: 'ui.svg' as PlatformCapabilityId,
        name: 'SVG Graphics',
        description: 'Scalable vector graphics for charts and diagrams',
        required: false,
        integrationRole: 'secondary',
        dependsOn: [],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'moderate',
        implementationHint: 'Use SVG elements for scalable graphics',
      },
      {
        capabilityId: 'ui.animation' as PlatformCapabilityId,
        name: 'Animation Support',
        description: 'Smooth transitions and interactive animations',
        required: false,
        integrationRole: 'auxiliary',
        dependsOn: ['ui.canvas' as PlatformCapabilityId],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'moderate',
        implementationHint: 'Use requestAnimationFrame or CSS animations',
      },
      {
        capabilityId: 'ui.interaction' as PlatformCapabilityId,
        name: 'User Interaction',
        description: 'Mouse, touch, and keyboard interaction handling',
        required: true,
        integrationRole: 'secondary',
        dependsOn: ['ui.canvas' as PlatformCapabilityId],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'moderate',
        implementationHint: 'Implement event handlers for user interactions',
      },
    ],
    integrationNotes:
      'Custom data visualization provides full control but requires more implementation effort',
  },

  // Offline Sync composition
  {
    complexCapability: 'networking.offline-sync' as PlatformCapabilityId,
    supportedPlatforms: [PlatformType.WEB, PlatformType.CAPACITOR],
    functionalCoverage: 'substantial',
    implementationComplexity: 'high',
    performanceComparison: 'worse',
    componentCapabilities: [
      {
        capabilityId: 'storage.local' as PlatformCapabilityId,
        name: 'Local Storage',
        description: 'Store data locally while offline',
        required: true,
        integrationRole: 'primary',
        dependsOn: [],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'minimal',
        implementationHint: 'Use localStorage or IndexedDB for offline data',
      },
      {
        capabilityId: 'networking.connectivity' as PlatformCapabilityId,
        name: 'Connectivity Detection',
        description: 'Detect online/offline status changes',
        required: true,
        integrationRole: 'secondary',
        dependsOn: [],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'minimal',
        implementationHint: 'Use navigator.onLine and online/offline events',
      },
      {
        capabilityId: 'networking.background-sync' as PlatformCapabilityId,
        name: 'Background Sync',
        description: 'Sync data when connectivity is restored',
        required: false,
        integrationRole: 'auxiliary',
        dependsOn: [
          'networking.connectivity' as PlatformCapabilityId,
          'storage.local' as PlatformCapabilityId,
        ],
        availablePlatforms: [PlatformType.WEB],
        implementationEffort: 'significant',
        implementationHint: 'Use service workers for background sync when available',
      },
      {
        capabilityId: 'storage.conflict-resolution' as PlatformCapabilityId,
        name: 'Conflict Resolution',
        description: 'Handle data conflicts during sync',
        required: true,
        integrationRole: 'auxiliary',
        dependsOn: ['storage.local' as PlatformCapabilityId],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'significant',
        implementationHint: 'Implement merge strategies for conflicting data',
      },
    ],
    integrationNotes:
      'Manual offline sync implementation requires careful consideration of data consistency',
  },

  // Advanced Notifications composition
  {
    complexCapability: 'system.rich-notifications' as PlatformCapabilityId,
    supportedPlatforms: [PlatformType.WEB, PlatformType.CAPACITOR],
    functionalCoverage: 'partial',
    implementationComplexity: 'medium',
    performanceComparison: 'worse',
    componentCapabilities: [
      {
        capabilityId: 'ui.toast' as PlatformCapabilityId,
        name: 'Toast Notifications',
        description: 'Simple in-app notification messages',
        required: true,
        integrationRole: 'primary',
        dependsOn: [],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'minimal',
        implementationHint: 'Create overlay elements for toast notifications',
      },
      {
        capabilityId: 'ui.sound' as PlatformCapabilityId,
        name: 'Sound Alerts',
        description: 'Audio notifications and alerts',
        required: false,
        integrationRole: 'auxiliary',
        dependsOn: [],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'minimal',
        implementationHint: 'Use HTML5 Audio API for notification sounds',
      },
      {
        capabilityId: 'ui.badge' as PlatformCapabilityId,
        name: 'Badge Indicators',
        description: 'Visual indicators for unread notifications',
        required: false,
        integrationRole: 'auxiliary',
        dependsOn: [],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'minimal',
        implementationHint: 'Update favicon or title for notification badges',
      },
      {
        capabilityId: 'storage.local' as PlatformCapabilityId,
        name: 'Notification Storage',
        description: 'Store notification history and preferences',
        required: false,
        integrationRole: 'auxiliary',
        dependsOn: [],
        availablePlatforms: [PlatformType.WEB, PlatformType.CAPACITOR, PlatformType.ELECTRON],
        implementationEffort: 'minimal',
        implementationHint: 'Use localStorage for notification persistence',
      },
    ],
    integrationNotes:
      'In-app notifications lack the persistence and attention-getting features of system notifications',
  },
];
