/**
 * Error codes for categorizing validation failures
 */
export enum ValidationErrorCode {
  REQUIRED = "REQUIRED",
  INVALID_FORMAT = "INVALID_FORMAT",
  INVALID_LENGTH = "INVALID_LENGTH",
  INVALID_ENUM = "INVALID_ENUM",
  INVALID_URL = "INVALID_URL",
  API_KEY_FORMAT = "API_KEY_FORMAT",
  DUPLICATE_NAME = "DUPLICATE_NAME",
  PROVIDER_SPECIFIC = "PROVIDER_SPECIFIC",
  CUSTOM_RULE = "CUSTOM_RULE",
}
