/**
 * Represents a migration that has been successfully applied to the database.
 * Matches the schema of the migrations tracking table.
 *
 * @example
 * ```typescript
 * const appliedMigration: AppliedMigration = {
 *   id: 1,
 *   filename: "001_create_users_table.sql",
 *   checksum: "sha256:abc123...",
 *   applied_at: "2025-08-23T16:45:00.000Z"
 * };
 * ```
 */
export interface AppliedMigration {
  /**
   * Auto-incremented primary key from the migrations table.
   */
  id: number;

  /**
   * Migration filename that was applied.
   * Must be unique in the migrations table.
   */
  filename: string;

  /**
   * Optional SHA-256 checksum of the migration file content.
   * Can be used to verify migration integrity.
   */
  checksum?: string;

  /**
   * ISO timestamp when the migration was successfully applied.
   * Generated by the database using CURRENT_TIMESTAMP.
   */
  applied_at: string;
}
