/**
 * Migration error codes for standardized migration error handling.
 * Maps migration-specific failures to application error categories.
 */
export enum MigrationErrorCode {
  // Migration file errors
  MIGRATION_FILE_NOT_FOUND = "MIGRATION_FILE_NOT_FOUND",
  MIGRATION_FILE_READ_ERROR = "MIGRATION_FILE_READ_ERROR",
  INVALID_MIGRATION_FILENAME = "INVALID_MIGRATION_FILENAME",
  DUPLICATE_MIGRATION_ORDER = "DUPLICATE_MIGRATION_ORDER",

  // Migration discovery errors
  MIGRATION_DIRECTORY_NOT_FOUND = "MIGRATION_DIRECTORY_NOT_FOUND",
  MIGRATION_DIRECTORY_ACCESS_ERROR = "MIGRATION_DIRECTORY_ACCESS_ERROR",
  NO_MIGRATIONS_FOUND = "NO_MIGRATIONS_FOUND",

  // Migration execution errors
  MIGRATION_EXECUTION_FAILED = "MIGRATION_EXECUTION_FAILED",
  MIGRATION_ROLLBACK_FAILED = "MIGRATION_ROLLBACK_FAILED",
  MIGRATION_SQL_ERROR = "MIGRATION_SQL_ERROR",
  MIGRATION_TIMEOUT = "MIGRATION_TIMEOUT",

  // Migration tracking errors
  TRACKING_TABLE_CREATE_FAILED = "TRACKING_TABLE_CREATE_FAILED",
  TRACKING_INSERT_FAILED = "TRACKING_INSERT_FAILED",
  TRACKING_QUERY_FAILED = "TRACKING_QUERY_FAILED",

  // Migration state errors
  MIGRATION_ALREADY_APPLIED = "MIGRATION_ALREADY_APPLIED",
  MIGRATION_OUT_OF_ORDER = "MIGRATION_OUT_OF_ORDER",
  PENDING_MIGRATION_EXISTS = "PENDING_MIGRATION_EXISTS",

  // General migration errors
  UNKNOWN_MIGRATION_ERROR = "UNKNOWN_MIGRATION_ERROR",
  MIGRATION_SYSTEM_ERROR = "MIGRATION_SYSTEM_ERROR",
}
