/**
 * Database error codes for standardized error handling.
 * Maps database-specific errors to application error categories.
 */
export enum DatabaseErrorCode {
  // Connection errors
  CONNECTION_FAILED = "CONNECTION_FAILED",
  CONNECTION_TIMEOUT = "CONNECTION_TIMEOUT",
  DATABASE_BUSY = "DATABASE_BUSY",
  DATABASE_LOCKED = "DATABASE_LOCKED",

  // Query errors
  QUERY_SYNTAX_ERROR = "QUERY_SYNTAX_ERROR",
  QUERY_EXECUTION_ERROR = "QUERY_EXECUTION_ERROR",
  INVALID_PARAMETERS = "INVALID_PARAMETERS",
  RESULT_SET_ERROR = "RESULT_SET_ERROR",

  // Constraint violations
  CONSTRAINT_VIOLATION = "CONSTRAINT_VIOLATION",
  UNIQUE_CONSTRAINT_VIOLATION = "UNIQUE_CONSTRAINT_VIOLATION",
  FOREIGN_KEY_CONSTRAINT_VIOLATION = "FOREIGN_KEY_CONSTRAINT_VIOLATION",
  CHECK_CONSTRAINT_VIOLATION = "CHECK_CONSTRAINT_VIOLATION",
  NOT_NULL_CONSTRAINT_VIOLATION = "NOT_NULL_CONSTRAINT_VIOLATION",

  // Transaction errors
  TRANSACTION_FAILED = "TRANSACTION_FAILED",
  TRANSACTION_ROLLBACK = "TRANSACTION_ROLLBACK",
  TRANSACTION_DEADLOCK = "TRANSACTION_DEADLOCK",

  // Permission and access errors
  PERMISSION_DENIED = "PERMISSION_DENIED",
  DATABASE_NOT_FOUND = "DATABASE_NOT_FOUND",
  TABLE_NOT_FOUND = "TABLE_NOT_FOUND",
  COLUMN_NOT_FOUND = "COLUMN_NOT_FOUND",

  // General errors
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  UNSUPPORTED_OPERATION = "UNSUPPORTED_OPERATION",
}
